import { Wine, SubscriptionPlan, Pairing, CorporateGift, GiftBasket } from './types';

export const INITIAL_WINES: Wine[] = [
  {
    id: 1,
    name: 'Château Margaux',
    variety: 'Cabernet Sauvignon',
    origin: 'Bordeaux, France',
    structure: 'Full-bodied',
    taste: 'Elegant, blackcurrant, cedar, tobacco',
    strength: '14.5%',
    vintage: 2018,
    price: 571.0,
    stock_quantity: 24,
    description: 'A legendary Bordeaux with incredible depth and aging potential.',
    featured: true,
    in_stock: true,
    image_url: '/wines/margaux.png',
  },
  {
    id: 2,
    name: 'Cloudy Bay',
    variety: 'Sauvignon Blanc',
    origin: 'Marlborough, New Zealand',
    structure: 'Crisp',
    taste: 'Citrus, passionfruit, grassy, gooseberry',
    strength: '13.5%',
    vintage: 2021,
    price: 615.0,
    stock_quantity: 21,
    description: "New Zealand's iconic Sauvignon Blanc. Vibrant and aromatic.",
    featured: true,
    in_stock: true,
    image_url: '/wines/cloudybay.png',
  },
  {
    id: 3,
    name: 'Kanonkop Pinotage',
    variety: 'Pinotage',
    origin: 'Stellenbosch, South Africa',
    structure: 'Rich',
    taste: 'Plum, coffee, chocolate, blackberry',
    strength: '14.5%',
    vintage: 2020,
    price: 345.0,
    stock_quantity: 16,
    description: "South Africa's flagship Pinotage. Bold and characterful.",
    featured: true,
    in_stock: true,
    image_url: '/wines/kanonkop.png',
  },
  {
    id: 4,
    name: 'Opus One',
    variety: 'Cabernet Sauvignon',
    origin: 'Napa Valley, USA',
    structure: 'Powerful',
    taste: 'Dark fruit, vanilla, oak, cassis',
    strength: '14.8%',
    vintage: 2018,
    price: 745.0,
    stock_quantity: 14,
    description: 'Napa Valley masterpiece from Robert Mondavi and Baron Philippe.',
    featured: true,
    in_stock: true,
    image_url: '/wines/opusone.png',
  },
  {
    id: 5,
    name: 'Kanonkop Kadette',
    variety: 'Cape Blend',
    origin: 'Stellenbosch, South Africa',
    structure: 'Medium',
    taste: 'Red berry, spice, vanilla, plum',
    strength: '14%',
    vintage: 2021,
    price: 499.0,
    stock_quantity: 20,
    description: 'Excellent entry-level Cape Blend. Perfect for everyday enjoyment.',
    featured: false,
    in_stock: true,
    image_url: '/wines/kanonkop-kadette.png',
  },
  {
    id: 6,
    name: 'Meerlust Rubicon',
    variety: 'Bordeaux Blend',
    origin: 'Stellenbosch, South Africa',
    structure: 'Complex',
    taste: 'Black fruit, cedar, spice, leather',
    strength: '14.2%',
    vintage: 2018,
    price: 273.0,
    stock_quantity: 17,
    description: "South Africa's iconic Bordeaux-style blend. Aged in French oak.",
    featured: false,
    in_stock: true,
    image_url: '/wines/meerlust.png',
  },
  {
    id: 7,
    name: 'La Torre',
    variety: "Montepulciano d'Abruzzo",
    origin: 'Italy (Abruzzo)',
    structure: 'Full-bodied',
    taste: 'Dark cherry, plum, earthy, with firm tannins',
    strength: '14% - 15%',
    vintage: 2020,
    price: 980.0,
    stock_quantity: 20,
    description: 'A classic Montepulciano from Tenuta Pescarnia with rich dark fruit and robust rustic character.',
    featured: false,
    in_stock: true,
    image_url: '/wines/la-torre.png',
  },
  {
    id: 8,
    name: 'The Reserve',
    variety: 'Red Blend',
    origin: 'South Africa (Tokalon Vineyard)',
    structure: 'Well-structured',
    taste: 'Blackcurrant, dark chocolate, hints of spice and oak',
    strength: '14% - 15%',
    vintage: 2021,
    price: 700.0,
    stock_quantity: 12,
    description: 'A distinguished red blend from the historic Tokalon Vineyard, aged in French oak barrels.',
    featured: false,
    in_stock: true,
    image_url: '/wines/the-reserve-red-blend.png',
  },
  {
    id: 9,
    name: 'Franschhoek Cellar Sauvignon Blanc',
    variety: 'Sauvignon Blanc',
    origin: 'South Africa (Franschhoek Valley)',
    structure: 'Crisp',
    taste: 'Crisp, tropical aromas, zesty citrus with bright acidity',
    strength: '13% ABV',
    vintage: 2021,
    price: 179.0,
    stock_quantity: 18,
    description: 'A vibrant and refreshing Sauvignon Blanc from the renowned cool-climate Franschhoek Valley.',
    featured: false,
    in_stock: true,
    image_url: '/wines/franschhoek-cellar-sauvignon-blanc.png',
  },
  {
    id: 10,
    name: 'Billingham Big Oak',
    variety: 'Red Blend',
    origin: 'Mozambique',
    structure: 'Full-bodied',
    taste: 'Blackberry, cassis, dried figs, toasted oak, vanilla, and warm spice',
    strength: '14.5% ABV',
    vintage: 2018,
    price: 527.0,
    stock_quantity: 8,
    description: 'A bold and richly structured red wine from Mozambique, aged in big oak barrels.',
    featured: false,
    in_stock: true,
    image_url: '/wines/billingham-big-oak-red.png',
  },
  {
    id: 11,
    name: 'Grand Vin de Bordeaux - Médoc',
    variety: 'Red Blend (Cabernet / Merlot)',
    origin: 'France (Bordeaux - Médoc)',
    structure: 'Full-bodied',
    taste: 'Blackcurrant, cedar, tobacco, earthy notes, subtle oak',
    strength: '13.5% ABV',
    vintage: 2019,
    price: 416.0,
    stock_quantity: 5,
    description: 'A prestigious Grand Vin offering powerful yet elegant expression of classic Bordeaux terroir.',
    featured: false,
    in_stock: true,
    image_url: '/wines/grand-vin-bordeaux-medoc.png',
  },
  {
    id: 12,
    name: 'Paco Milan',
    variety: 'Tempranillo Blend',
    origin: 'Spain (Hacienda Telespino)',
    structure: 'Medium',
    taste: 'Dark cherry, plum, blackberry, vanilla, spice, leather',
    strength: '14% ABV',
    vintage: 2017,
    price: 319.0,
    stock_quantity: 15,
    description: 'A distinguished Spanish red from Hacienda Telespino showcasing elegance and lingering finish.',
    featured: false,
    in_stock: true,
    image_url: '/wines/paco-milan.png',
  },
];

export const INITIAL_SUBSCRIPTIONS: SubscriptionPlan[] = [
  {
    id: 1,
    tier_name: 'explorer',
    display_name: 'Essential Elegance Box',
    tagline: 'Discover. Enjoy. Belong.',
    price: 499.0,
    wines_per_month: 2,
    description: 'Curated selections for the curious wine lover looking to explore quality vintages.',
    features: [
      '2 Premium Wines delivered monthly',
      'Sommelier Tasting & Cellar Notes',
      'Free Doorstep Delivery in Eswatini',
      'Member Discounts on Full Cases',
    ],
    packaging: 'Branded Kraft Delivery Box',
    savings_percent: 0,
    is_popular: false,
  },
  {
    id: 2,
    tier_name: 'connoisseur',
    display_name: 'Vineyard Voyager Box',
    tagline: 'Exceptional Wines. Exclusive Access.',
    price: 999.0,
    wines_per_month: 4,
    description: 'Hand-picked reserve bottles from top estates with gourmet tasting accompaniments.',
    features: [
      '4 Reserve Wines delivered monthly',
      'Detailed Pairing & Recipe Guides',
      'Priority Delivery across Eswatini',
      'Early Access to New Releases',
      '10% Off All Bottle Orders',
    ],
    packaging: 'Luxury Magnetic Gift Box',
    savings_percent: 20,
    is_popular: true,
  },
  {
    id: 3,
    tier_name: 'collector',
    display_name: 'Luxury Reserve Box',
    tagline: 'The Finest. The Rarest. Yours.',
    price: 1999.0,
    wines_per_month: 6,
    description: 'Rare vintages and cellar-worthy masterpieces selected directly by our head sommelier.',
    features: [
      '6 Rare & Award-Winning Vintages',
      'Dedicated Personal Wine Advisor',
      'VIP Invitation to Private Tasting Events',
      'Bespoke Wooden Presentation Case',
      '15% Off Everything in Store',
    ],
    packaging: 'Premium Leatherette Box',
    savings_percent: 30,
    is_popular: false,
  },
  {
    id: 4,
    tier_name: 'grand',
    display_name: 'Grand Reserve Society',
    tagline: "More Than Wine. It's a Lifestyle.",
    price: 4999.0,
    wines_per_month: 12,
    description: 'The ultimate luxury wine club in Southern Africa with private sommelier tastings.',
    features: [
      '12 Iconic Collector Vintages monthly',
      'Private Sommelier Wine Tasting at Home',
      'First Allocation on Rare Imports',
      'Custom Engraved Wine Storage Box',
      '20% Lifetime VIP Discount',
    ],
    packaging: 'Handcrafted Wooden Wine Case',
    savings_percent: 40,
    is_popular: false,
  },
];

export const INITIAL_PAIRINGS: Pairing[] = [
  {
    id: 1,
    name: 'Artisan Cheese Board',
    description: 'Aged cheddar, creamy brie, and gorgonzola blue cheese with gourmet crackers and fig preserve.',
    price: 450.0,
    compatible_wines: 'Kanonkop Pinotage, Meerlust Rubicon',
    in_stock: true,
    image_url: '/pairings/artisan-cheese-board.png',
  },
  {
    id: 2,
    name: 'Dark Chocolate Truffles',
    description: 'Handmade Belgian 70% dark chocolate truffles dusted with sea salt and cocoa nibs.',
    price: 342.0,
    compatible_wines: 'Grand Vin de Bordeaux - Médoc, Opus One',
    in_stock: true,
    image_url: '/pairings/dark-chocolate-truffles.png',
  },
  {
    id: 3,
    name: 'Biltong Platter',
    description: 'Traditional prime beef South African sliced biltong and droëwors selection.',
    price: 360.0,
    compatible_wines: 'Cabernet Sauvignon, Pinotage, Shiraz',
    in_stock: true,
    image_url: '/pairings/biltong-platter.png',
  },
  {
    id: 4,
    name: 'Mediterranean Olive Medley',
    description: 'Marinated Kalamata and giant green olives with fresh rosemary, garlic, and cold-pressed olive oil.',
    price: 100.0,
    compatible_wines: 'Franschhoek Cellar Sauvignon Blanc, Cloudy Bay',
    in_stock: true,
    image_url: '/pairings/mediterranean-olives.png',
  },
];

export const INITIAL_CORPORATE_GIFTS: CorporateGift[] = [
  {
    id: 1,
    name: 'Executive Gift Box',
    tier: 'Executive',
    description: '3 Premium Wines paired with artisan chocolates and custom gift card.',
    features: '3 Premium Wines, Personalised Card, Elegant Ribbon Box',
    price: 1499.0,
    wines_included: 3,
    is_active: true,
    image_url: '/corporate/executive-gift-box.png',
  },
  {
    id: 2,
    name: 'Boardroom Collection',
    tier: 'Boardroom',
    description: '6 Reserve Wines with gourmet accompaniments and crystal decanter.',
    features: '6 Reserve Wines, Gourmet Hamper, Crystal Decanter, Custom Company Branding',
    price: 3499.0,
    wines_included: 6,
    is_active: true,
    image_url: '/corporate/boardroom-collection.png',
  },
  {
    id: 3,
    name: "Chairman's Reserve",
    tier: "Chairman's Reserve",
    description: '12 Rare Vintages in handcrafted wooden case with private tasting session.',
    features: '12 Rare Vintages, Handcrafted Wooden Case, Private Sommelier Tasting Event',
    price: 7999.0,
    wines_included: 12,
    is_active: true,
    image_url: '/corporate/chairmans-reserve.png',
  },
];

export const INITIAL_GIFT_BASKETS: GiftBasket[] = [
  {
    id: 1,
    name: 'Classic Elegance Basket',
    description: 'The perfect gift for any celebration, milestone, or host gift.',
    features: '2 wines, artisan chocolates, gourmet cheese selection',
    price: 699.0,
    wines_included: 2,
    is_active: true,
    image_url: '/baskets/classic-elegance-basket.png',
  },
  {
    id: 2,
    name: 'Premium Indulgence Basket',
    description: 'Luxury gift hamper for discerning wine and artisanal food lovers.',
    features: '3 reserve wines, charcuterie, artisan crackers & olive tapenade',
    price: 1299.0,
    wines_included: 3,
    is_active: true,
    image_url: '/baskets/premium-indulgence-basket.png',
  },
  {
    id: 3,
    name: 'Grand Celebration Hamper',
    description: 'The ultimate celebratory wine and delicacy experience with luxury accessories.',
    features: '6 estate wines, gourmet hamper, crystal glasses & wine accessories',
    price: 2499.0,
    wines_included: 6,
    is_active: true,
    image_url: '/baskets/grand-celebration-hamper.png',
  },
];
